<table align="left" width=100%>
    <tr>
        <td width="10%">
            <img src="in_class.png">
        </td>
        <td>
            <div align="center">
                <font color="#21618C" size=8px>
                  <b> MANDATORY ASSIGNMENT_3<br> </b>
                </font>
            </div>
        </td>
    </tr>
</table>

##  Table of Content

1. **[One Dimensional Array](#1D)**
2. **[Two Dimensional Array](#2D)**
3. **[Stacking](#Stacking)**
4. **[Splitting](#Splitting)**
5. **[For Loop](#loop)**

**Import the NumPy library before solving the exercises**

### Let's begin with some hands-on practice exercises

<a id="1D"> </a>
## 1. One Dimensional Array

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>1. Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below: (or create your own list)**<br>

    list_temperature = [3.04, 1.65, 5.76, 1.66, 1.54, 4.69, 2.68]

In [3]:
# type your code here
import numpy as np
list_temperature = [3.04, 1.65, 5.76, 1.66, 1.54, 4.69, 2.68]
new_array = np.array(list_temperature)
print("Numpy array created using passed list is ",new_array," and type is ", type(new_array))

Numpy array created using passed list is  [3.04 1.65 5.76 1.66 1.54 4.69 2.68]  and type is  <class 'numpy.ndarray'>


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>2. Create a 1D array of weights of 10 students and retrieve all the weights greater than 68</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the weights given below: (or create your own list)**

    weights = [74.2, 85, 74, 67.9, 52, 70.5, 86, 51.8, 64, 82]

In [3]:
# type your code here
weights = [74.2, 85, 74, 67.9, 52, 70.5, 86, 51.8, 64, 82]
np_weights = np.array(weights)
print("Elements which are greater than 68 in the array {} are {}".format(np_weights, np_weights[ np_weights > 68 ]))

Elements which are greater than 68 in the array [74.2 85.  74.  67.9 52.  70.5 86.  51.8 64.  82. ] are [74.2 85.  74.  70.5 86.  82. ]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>3. Write a code to generate 10 random integers between 20 to 40 (Is it possible to generate same random numbers everytime? If yes, describe the function)
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [4]:
# type your code here
np.random.seed(10)
print(np.random.randint(20,40,10))

[29 24 35 20 37 36 37 28 29 20]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>4. Write a program to get the fifth power of the first five positive integers
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [5]:
# type your code here
np_array1 = np.arange(1,6)
print("5th power array of first 5 positive interst {} is {}".format(np_array1, np_array1**5))

5th power array of first 5 positive interst [1 2 3 4 5] is [   1   32  243 1024 3125]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>5. Write a program to create an array of all the odd integers from 50 to 100 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [6]:
# type your code here
np_array2 = np.arange(50,101)
print(np_array2[ np_array2 % 2 != 0])

[51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95 97
 99]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>6. Write a program to calculate the sum of each column </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below: (or create your own array)**

    A = [[1, 4, 8], [5, 7, 3], [9, 14, 2]]

In [8]:
# type your code here
A = [[1, 4, 8], [5, 7, 3], [9, 14, 2]]
np_array3 = np.array(A)
print("Sum of column 0 is {}".format(np_array3[0][0] + np_array3[1][0] + np_array3[2][0]))
print("Sum of column 1 is {}".format(np_array3[0][1] + np_array3[1][1] + np_array3[2][1]))
print("Sum of column 2 is {}".format(np_array3[0][2] + np_array3[1][2] + np_array3[2][2]))

Sum of column 0 is 15
Sum of column 1 is 25
Sum of column 2 is 13


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>7. Write a code to get the element-wise remainder of an array after division by 8 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below:**<br>
    
    num = [42, 87, 90, 14, 32, 75, 61, 80, 92]

In [13]:
# type your code here
num = [42, 87, 90, 14, 32, 75, 61, 80, 92]
np_array3 = np.array(num)
print("Element wise remainder after diving array {} by 8 is {}".format(num, np_array3 % 8))

Element wise remainder after diving array [42, 87, 90, 14, 32, 75, 61, 80, 92] by 8 is [2 7 2 6 0 3 5 0 4]


<a id="2D"> </a>
## 2. Two Dimensional Array

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>8. Create a 2D numpy array from a 1D array of 20 elements of your choice. Further, subset the first 5 elements from the second element of a resulting 2D array 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [22]:
# type your code here
# Create a 2D numpy array from a 1D array of 20 elements of your choice
np_array4 = np.arange(0,20)
print("1D array from numpy is {} and type is {}".format(np_array4, type(np_array4)))
np_array5 = np_array4.reshape(2,10)
print("1D array {} \ntransormed into 2D array \n{}".format(np_array4, np_array5))

#Further, subset the first 5 elements from the second element of a resulting 2D array 
print("Subset of frist 5 elements from 2nd element of 2d array {} is {}".format(np_array5, np_array5[1,2:7]))

1D array from numpy is [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] and type is <class 'numpy.ndarray'>
1D array [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] 
transormed into 2D array 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
Subset of frist 5 elements from 2nd element of 2d array [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] is [12 13 14 15 16]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>9. Write a program to find common values between two arrays 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below:**<br>

    prices_monday = [10, 30, 50, 60, 90]

    prices_tuesday = [50, 20, 80, 125, 10, 70]

In [38]:
# type your code here
prices_monday = [10, 30, 50, 60, 90]
prices_tuesday = [50, 20, 80, 125, 10, 70]
np_prices_monday  = np.array(prices_monday)
np_prices_tuesday = np.array(prices_tuesday)

common_price_elements = []

check_common_price = lambda price : price in np_prices_tuesday        
common_price_elements = [ price for price in np_prices_monday if check_common_price(price) ]         
print("{} are a common element between {} and {}".format(common_price_elements, np_prices_monday, np_prices_tuesday))

[10, 50] are a common element between [10 30 50 60 90] and [ 50  20  80 125  10  70]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>10. Write a program to find BMI of the patients whose height and weight is provided in the list given below 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below:**<br>

    list of weights (in kg)
    weights = [57, 69, 54, 65 ,71, 62, 56]

    list of heights (in m)<br>
    heights = [1.59, 1.75, 1.66, 1.74, 1.64, 1.72, 1.53] 

BMI = weights/(heights*2)

In [41]:
# type your code here
weights = [57, 69, 54, 65 ,71, 62, 56]
heights = [1.59, 1.75, 1.66, 1.74, 1.64, 1.72, 1.53] 

np_weights = np.array(weights)
np_heights = np.array(heights)

print("BMI is \n{}".format(np_weights / (np_heights * 2)))

BMI is 
[17.9245283  19.71428571 16.26506024 18.67816092 21.64634146 18.02325581
 18.30065359]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>11. Write a program to add a new column ([5,7]) at the last position in the array given below 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**

    array1 = [[[3, 4], [8, 2],[5, 9]]]

In [81]:
# type your code here
np_array6 = np.array([[[3, 4], [8, 2],[5, 9]]])
new_column = np.array([[[5,6]]])
print(np.hstack((np_array6,new_column)))

[[[3 4]
  [8 2]
  [5 9]
  [5 6]]]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>12. Write a code to print the identity matrix of order 5</b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [4]:
# type your code here
print(np.identity(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>13. Write a program to transpose a matrix 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the matrix given below:**
    
    M = [[15, 17, 45, 56], [7, 42, 15, 63], [54, 3, 61, 41], [0, 87, 16, 20]]

In [88]:
# type your code here
m_array =  np.array([[15, 17, 45, 56], [7, 42, 15, 63], [54, 3, 61, 41], [0, 87, 16, 20]])
print("Transposed array of \n\n{} \n\nis \n\n{}".format(m_array, m_array.T))

Transposed array of 

[[15 17 45 56]
 [ 7 42 15 63]
 [54  3 61 41]
 [ 0 87 16 20]] 

is 

[[15  7 54  0]
 [17 42  3 87]
 [45 15 61 16]
 [56 63 41 20]]


<a id="Stacking"> </a>
## 3. Stacking

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>14. Write a program to combine the two arrays vertically</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the arrays given below: (or create your own array)**<br>

    A1 = [[5, 9], [7, 6]]

    A2 = [[8,-7], [0,4]]

Combine the array A2 with A1

In [94]:
# type your code here
a1_array = np.array([[5, 9], [7, 6]])
a2_array = np.array([[8,-7], [0,4]])
print("Stacking \n\n{} \n\nand \n\n{} \n\nvertically \n\n{}".format(a1_array, a2_array, np.vstack((a1_array, a2_array))))

Stacking 

[[5 9]
 [7 6]] 

and 

[[ 8 -7]
 [ 0  4]] 

vertically 

[[ 5  9]
 [ 7  6]
 [ 8 -7]
 [ 0  4]]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>15. Write a code to combine the two arrays horizontally</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the arrays given below: (or create your own array)**

    A1 = [[-81, 75, 40], [27, 67, 52]]

    A2 = [[15, 54], [39, 56]]

Combine the array A2 with A1

In [95]:
# type your code here
a1_array = np.array([[-81, 75, 40], [27, 67, 52]])
a2_array = np.array([[15, 54], [39, 56]])
print("Stacking \n\n{} \n\nand \n\n{} \n\nhorizontally \n\n{}".format(a1_array, a2_array, np.hstack((a1_array, a2_array))))

Stacking 

[[-81  75  40]
 [ 27  67  52]] 

and 

[[15 54]
 [39 56]] 

horizontally 

[[-81  75  40  15  54]
 [ 27  67  52  39  56]]


<a id="Splitting"> </a>
## 4. Splitting

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>16. Write a code to divide the array into three sub-arrays containing
                       equal number of rows</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**<br>

    A = [[4, 7], [2, -3], [8, 1], [0, 9], [5,-1], [8, 3]]

In [117]:
# type your code here
np_array7 = np.array([[4, 7], [2, -3], [8, 1], [0, 9], [5,-1], [8, 3]])
print(np.split(np_array7, 3))

[array([[ 4,  7],
       [ 2, -3]]), array([[8, 1],
       [0, 9]]), array([[ 5, -1],
       [ 8,  3]])]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>17. Write a program to divide the array into two sub-arrays containing equal number of columns
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**

    B = [[8, 7, 0, 9], [2, -3, 5, 10], [8, 5, -1,3]]

In [119]:
# type your code here
np_array8 = np.array([[8, 7, 0, 9], [2, -3, 5, 10], [8, 5, -1,3]])
print(np.split(np_array8, 2, axis = 1))

[array([[ 8,  7],
       [ 2, -3],
       [ 8,  5]]), array([[ 0,  9],
       [ 5, 10],
       [-1,  3]])]


<a id="loop"> </a>
## 5. For Loop

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>18. Write a program to perform one-to-one mapping of the two lists</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below: (or create your own lists)**<br>

    L1 = [45, 67, 56, 71, 54, 62, 56]

    L2 = [21, 52, 64, 10, 49, 74, 26]

In [16]:
# type your code here
L1 = [45, 67, 56, 71, 54, 62, 56]
L2 = [21, 52, 64, 10, 49, 74, 26]

mapped_list = {}

for index in range(len(L1)):
    mapped_list[L1[index]] = L2[index]
    
print(mapped_list)

{45: 21, 67: 52, 56: 26, 71: 10, 54: 49, 62: 74}


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>19. Define a for loop to apply the function (2x-1)/(x+5) on every element of an array </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below:**
    
    numbers = [6, 5, 3, 15]

In [3]:
# type your code here
func = lambda x : (2 * x - 1) / (x + 5)

numbers = [6, 5, 3, 15]
for num in numbers:
    print("Num is {} and function output is {}".format(num, func(num)))

Num is 6 and function output is 1.0
Num is 5 and function output is 0.9
Num is 3 and function output is 0.625
Num is 15 and function output is 1.45


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>20. Create an identity matrix with n dimensions (take input from the user). Fill the diagonals of that matrix with the multiples of the number provided by the user; take another input from the user. Consider the output below as an example </b>
                </font>
            </div>
        </td>
    </tr>
</table>

<table align="center">
    <td height = '100', width = '700'>
          <img src="que 20.png">
        </td>
</table>

In [14]:
# type your code here

matrix_order = 1

while matrix_order > 0 :
    matrix_order = int(input("Enter order of matrix of square matrix"))
    matrix = np.ones((matrix_order, matrix_order))
    np.fill_diagonal(matrix, matrix_order)
    print(matrix)



Enter order of matrix of square matrix 3


[[3. 1. 1.]
 [1. 3. 1.]
 [1. 1. 3.]]


Enter order of matrix of square matrix 2


[[2. 1.]
 [1. 2.]]


Enter order of matrix of square matrix 1


[[1.]]


Enter order of matrix of square matrix 0


[]
