<table align="center" width=100%>
    <tr>
        <td width="15%">
            <img src="homework.png">
        </td>
        <td>
            <div align="center">
                <font color="#21618C" size=8px>
                    <b> OPTIONAL-ASSIGNMENT_3<br>
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

### Let's begin with some hands-on practice exercises

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>1. Create an array of integers from 20 to 2 with a step of -2
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [2]:
# Write your code here

import numpy as np
print("Array of integers from 20 to 2 with step of -2 is {}".format(np.arange(20, 1, -2)))

Array of integers from 20 to 2 with step of -2 is [20 18 16 14 12 10  8  6  4  2]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>2. Find the minimum value along each of the rows
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

#### Create a 2D Numpy array from list of lists

    num_array = np.array([[110, 102, 183],
                     [140, 175, 106],
                     [170, 195, 117],
                     [192, 140, 195]])

In [12]:
# Write your code here

num_array = np.array([[110, 102, 183],
                 [140, 175, 106],
                 [170, 195, 117],
                 [192, 140, 195]])
print(num_array[0].min())
print(num_array[1].min())
print(num_array[2].min())
print(num_array[3].min())

102
106
117
140


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>3. Replace all odd numbers in the array with -2
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below**<br>
    
       num_array = np.array([0, 31, 42, 43, 34, 45, 26, 27, 38, 94, 65, 78, 76])

In [13]:
# Write your code here
num_array = np.array([0, 31, 42, 43, 34, 45, 26, 27, 38, 94, 65, 78, 76])
num_array[ num_array % 2 != 0 ] = -2
print(num_array)

[ 0 -2 42 -2 34 -2 26 -2 38 94 -2 78 76]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>4. Replace all odd numbers in the array 'num_array' with -2 without changing the original array
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below**<br>

    num_array = np.array([0, 31, 42, 43, 34, 45, 26, 27, 38, 94, 65, 78, 76])

In [17]:
# Write your code here
num_array = np.array([0, 31, 42, 43, 34, 45, 26, 27, 38, 94, 65, 78, 76])
dummy_array = num_array.copy()
dummy_array[ dummy_array % 2 != 0 ] = -2
print("Original array ",num_array)
print("New array ",dummy_array)

Original array  [ 0 31 42 43 34 45 26 27 38 94 65 78 76]
New array  [ 0 -2 42 -2 34 -2 26 -2 38 94 -2 78 76]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>5. Stack two arrays vertically
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**<br>

    quantity1 = np.arange(10).reshape(2,-1)
    quantity2 = np.repeat(1, 10).reshape(2,-1)

In [19]:
# Write your code here
quantity1 = np.arange(10).reshape(2,-1)
quantity2 = np.repeat(1, 10).reshape(2,-1)
print(quantity1)
print(quantity2)
np.vstack((quantity1, quantity2))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>6. Get common elements from the two arrays
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**<br>

    age_a = np.array([11,12,13,22,23,44,43,24,45,36])
    age_b = np.array([17,22,13,22,47,34,39,44,29,28])

In [25]:
# Write your code here
age_a = np.array([11,12,13,22,23,44,43,24,45,36])
age_b = np.array([17,22,13,22,47,34,39,44,29,28])
print(age_a)
print(age_b)
check_common_elements = lambda agea : agea in age_b        
common_elements = [ agea for agea in age_a if check_common_elements(agea) ]         
print("{} are a common element between {} and {}".format(common_elements, age_a, age_b))

[11 12 13 22 23 44 43 24 45 36]
[17 22 13 22 47 34 39 44 29 28]
[13, 22, 44] are a common element between [11 12 13 22 23 44 43 24 45 36] and [17 22 13 22 47 34 39 44 29 28]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>7. Remove all the elements from num_array1 that are present in num_array2
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**<br>

    num_array1 = np.array([1,2,3,4,5])
    num_array2 = np.array([5,6,7,8,9])

In [38]:
# Write your code here
num_array1 = np.array([1,2,3,4,5])
num_array2 = np.array([5,6,7,8,9])
print(num_array1)
check_common_elements = lambda num : num not in num_array2        
num_array1 = np.array([ num for num in num_array1 if check_common_elements(num) ])         
print("{}".format(num_array1))

[1 2 3 4 5]
[1 2 3 4]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>8. Get the positions where elements of two arrays match
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**<br>

    num_array1 = np.array([1,2,3,2,3,4,3,4,5,6])
    num_array2 = np.array([7,2,10,2,7,4,9,4,9,8])

In [54]:
# Write your code here
num_array1 = np.array([1,2,3,4,5])
num_array2 = np.array([5,6,7,8,9])
print(num_array1)
check_common_elements = lambda num : num in num_array2    
common_element_map = ([ (num_array1.tolist().index(num), num_array2.tolist().index(num)) for num in num_array1 if check_common_elements(num) ] )      
print("{}".format(common_element_map))

[1 2 3 4 5]
[(4, 0)]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>9. Reverse each of the rows of the 2D array
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**<br>

    num_array1 = np.arange(16).reshape(4,4)

In [75]:
# Write your code here
num_array1 = np.arange(16).reshape(4,4)
print(num_array1)
num_array1[0] = num_array1[0][::-1]
num_array1[1] = num_array1[1][::-1]
num_array1[2] = num_array1[2][::-1]
num_array1[3] = num_array1[3][::-1]
print(num_array1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


# <table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>10. Swap row 1 and row 2 in the given array
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**<br>
   
       num_array1 = np.arange(9).reshape(3,3)

In [105]:
# Write your code here
num_array1 = np.arange(9).reshape(3,3)
print(num_array1)
num_array11 = np.vsplit(num_array1, [1,2])
num_array1 = np.vstack((num_array11[1], num_array11[0],num_array11[2]))
print(num_array1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]


## 