In [25]:
import numpy as np
list2 = [
    [
        [11,31],
        [12,32],
        [13,33],
        [14,34]
    ],
    [
        [15,35],
        [16,36],
        [17,37],
        [18,38]
    ],
    [
        [19,39],
        [20,40],
        [21,41],
        [22,42]
    ]
]

np342 = np.array(list2)
print(np342)
print(np342.shape)

[[[11 31]
  [12 32]
  [13 33]
  [14 34]]

 [[15 35]
  [16 36]
  [17 37]
  [18 38]]

 [[19 39]
  [20 40]
  [21 41]
  [22 42]]]
(3, 4, 2)


In [26]:
np342a = np.arange(11,23).reshape(3,4)
np342b = np.arange(31,43).reshape(3,4)
np324 = np.stack((np342a, np342b), axis = 1)
print(np324)
print(np324.shape)

[[[11 12 13 14]
  [31 32 33 34]]

 [[15 16 17 18]
  [35 36 37 38]]

 [[19 20 21 22]
  [39 40 41 42]]]
(3, 2, 4)


In [27]:
np234 = np.stack((np342a, np342b), axis = 0)
print(np234)
print(np234.shape)

[[[11 12 13 14]
  [15 16 17 18]
  [19 20 21 22]]

 [[31 32 33 34]
  [35 36 37 38]
  [39 40 41 42]]]
(2, 3, 4)
